app = 'searchpahe'
primary_region = 'ams'

[build]


[[mounts]]
source = 'anime_data_base'
destination = '/mnt/anime_data_base'

[http_service]
internal_port = 8081
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
